name: Mongo Backup

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Run mongodump in Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/backup \
            mongo:7 \
            sh -c 'mongodump --uri="${{ secrets.MONGODB_URI }}" --archive=/backup/backup.gz --gzip'

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mongo-backup
          path: backup.gz
